DELETE FROM DANE_WYPOZYCZENIA;
DELETE FROM KONTO;
DELETE FROM WYPOZYCZENIE;
DELETE FROM KLIENT;
DELETE FROM EGZEMPLARZ;
DELETE FROM FILMY;
DELETE FROM REZYSER;
DELETE FROM GATUNEK;

DROP SEQUENCE GatunekSeq;
CREATE SEQUENCE GatunekSeq;

INSERT INTO GATUNEK VALUES (GatunekSeq.NEXTVAL, 'akcja');
INSERT INTO GATUNEK VALUES (GatunekSeq.NEXTVAL, 'animowany');
INSERT INTO GATUNEK VALUES (GatunekSeq.NEXTVAL, 'biograficzny');
INSERT INTO GATUNEK VALUES (GatunekSeq.NEXTVAL, 'dramat');
INSERT INTO GATUNEK VALUES (GatunekSeq.NEXTVAL, 'fantasy');
INSERT INTO GATUNEK VALUES (GatunekSeq.NEXTVAL, 'historyczny');
INSERT INTO GATUNEK VALUES (GatunekSeq.NEXTVAL, 'horror');
INSERT INTO GATUNEK VALUES (GatunekSeq.NEXTVAL, 'komedia');
INSERT INTO GATUNEK VALUES (GatunekSeq.NEXTVAL, 'musical');
INSERT INTO GATUNEK VALUES (GatunekSeq.NEXTVAL, 'science-fiction');
INSERT INTO GATUNEK VALUES (GatunekSeq.NEXTVAL, 'sportowy');
INSERT INTO GATUNEK VALUES (GatunekSeq.NEXTVAL, 'thriller');
INSERT INTO GATUNEK VALUES (GatunekSeq.NEXTVAL, 'western');
INSERT INTO GATUNEK VALUES (GatunekSeq.NEXTVAL, 'wojenny');

DROP SEQUENCE RezyserSeq;
CREATE SEQUENCE RezyserSeq;

INSERT INTO REZYSER VALUES(RezyserSeq.NEXTVAL, 'Frank Darabont');
INSERT INTO REZYSER VALUES(RezyserSeq.NEXTVAL, 'Olivier Nakache');
INSERT INTO REZYSER VALUES(RezyserSeq.NEXTVAL, 'Francis Ford Coppola');
INSERT INTO REZYSER VALUES(RezyserSeq.NEXTVAL, 'Robert Zemeckis');
INSERT INTO REZYSER VALUES(RezyserSeq.NEXTVAL, 'Peter Jackson');
INSERT INTO REZYSER VALUES(RezyserSeq.NEXTVAL, 'Quentin Tarantino');
INSERT INTO REZYSER VALUES(RezyserSeq.NEXTVAL, 'Christopher Nolan');
INSERT INTO REZYSER VALUES(RezyserSeq.NEXTVAL, 'Rob Minkoff');
INSERT INTO REZYSER VALUES(RezyserSeq.NEXTVAL, 'Luc Besson');
INSERT INTO REZYSER VALUES(RezyserSeq.NEXTVAL, 'Roman Polański');

DROP SEQUENCE FilmySeq;
CREATE SEQUENCE FilmySeq;

INSERT INTO FILMY VALUES(FilmySeq.NEXTVAL, 'Skazani na Shawshank', 'Adaptacja opowiadania Stephena Kinga. Historia nies�usznie skazanego na do�ywocie bankiera, kt�ry musi prze�y� w brutalnym �wiecie rz�dzonym przez stra�nik�w i wsp��wi��ni�w.',
                      3, '1994-09-10', 4, 1);
INSERT INTO FILMY VALUES(FilmySeq.NEXTVAL, 'Zielona mila', 'Emerytowany stra�nik wi�zienny opowiada przyjaci��ce o niezwyk�ym m��czy�nie, kt�rego skazano na �mier� za zab�jstwo dw�ch 9-letnich dziewczynek.',
                       4, '1999-12-06', 4, 1);
INSERT INTO FILMY VALUES(FilmySeq.NEXTVAL, 'Nietykalni', 'Sparali�owany milioner zatrudnia do opieki m�odego ch�opaka z przedmie�cia, kt�ry w�a�nie wyszed� z wi�zienia.',
                       2, '2011-09-23', 8, 2);
INSERT INTO FILMY VALUES(FilmySeq.NEXTVAL, 'Ojciec chrzestny', 'Opowie�� o nowojorskiej rodzinie mafijnej. Starzej�cy si� Don Corleone pragnie przekaza� w�adz� swojemu synowi.',
                       5, '1972-03-15', 4, 3);
INSERT INTO FILMY VALUES(FilmySeq.NEXTVAL, 'Ojciec chrzestny II', 'Rok 1917. M�ody Vito Corleone stawia pierwsze kroki w mafijnym �wiecie Nowego Jorku. Ponad 40 lat p��niej jego syn Michael walczy o interesy i dobro rodziny.',
                       6, '1974-12-12', 4, 3);
INSERT INTO FILMY VALUES(FilmySeq.NEXTVAL, 'Ojciec chrzestny III', 'Rok 1979. Starzej�cy si� Michael Corleone chce zalegalizowa� swoje interesy i wyprowadzi� rodzin� z mafijnego �wiata.',
                       2, '1990-12-20', 4, 3);
INSERT INTO FILMY VALUES(FilmySeq.NEXTVAL, 'Forrest Gump', 'Historia �ycia Forresta, ch�opca o niskim ilorazie inteligencji z niedow�adem ko�czyn, kt�ry staje si� miliarderem i bohaterem wojny w Wietnamie.',
                       3, '1994-06-23', 4, 4);
INSERT INTO FILMY VALUES(FilmySeq.NEXTVAL, 'W�adca Pier�cieni: Dru�yna Pier�cienia', 'Podr�� hobbita z Shire i jego o�miu towarzyszy, kt�rej celem jest zniszczenie pot��nego pier�cienia po��danego przez Czarnego W�adc� - Saurona.',
                       1, '2001-12-10', 5, 5);
INSERT INTO FILMY VALUES(FilmySeq.NEXTVAL, 'W�adca Pier�cieni: Dwie wie�e', 'Dru�yna Pier�cienia zostaje rozbita, lecz zdesperowany Frodo za wszelk� cen� chce wype�ni� powierzone mu zadanie. Aragorn z towarzyszami przygotowuje si�, by odeprze� atak hord Sarumana.',
                       4, '2002-12-05', 5, 5);
INSERT INTO FILMY VALUES(FilmySeq.NEXTVAL, 'W�adca Pier�cieni: Powr�t kr�la', 'Zwie�czenie filmowej trylogii wg powie�ci Tolkiena. Aragorn jednoczy si�y �r�dziemia, szykuj�c si� do bitwy, kt�ra ma odwr�ci� uwag� Saurona od pod��aj�cych w kierunku G�ry Przeznaczenia hobbit�w.',
                       5, '2003-12-01', 5, 5);
INSERT INTO FILMY VALUES(FilmySeq.NEXTVAL, 'Hobbit: Niezwyk�a podr��', 'Hobbit Bilbo Baggins wyrusza w niebezpieczn� podro�, by wraz z czarodziejem Gandalfem i trzynastoma krasnoludami pokona� smoka Smauga.',
                       5, '2012-11-28', 5, 5);
INSERT INTO FILMY VALUES(FilmySeq.NEXTVAL, 'Hobbit: Pustkowie Smauga', 'Hobbit Bilbo Baggins razem z Gandalfem oraz trzynastoma krasnoludami zmierza do legowiska smoka Smauga. Bohaterowie chc� pokona� besti� i odebra� jej z�oto, kt�re ukrad�a.',
                       5, '2013-12-02', 5, 5);
INSERT INTO FILMY VALUES(FilmySeq.NEXTVAL, 'Hobbit: Bitwa Pi�ciu Armii', 'Krasnoludy z Ereboru odzyskuj� ojczyzn�, �ci�gaj�c gniew smoka. Wolne istoty �r�dziemia ��cz� si�y przeciwko Sauronowi, kt�ry wysy�a legiony ork�w na Samotn� G�r�.',
                       5, '2014-12-01', 5, 5);
INSERT INTO FILMY VALUES(FilmySeq.NEXTVAL, 'Pulp Fiction', 'Przemoc i odkupienie w opowie�ci o dw�ch p�atnych mordercach pracuj�cych na zlecenie mafii, �onie gangstera, bokserze i parze okradaj�cej ludzi w restauracji.',
                       4, '1994-05-12', 4, 6);
INSERT INTO FILMY VALUES(FilmySeq.NEXTVAL, 'B�karty wojny', 'W okupowanej przez nazist�w Francji oddzia� z�o�ony z Amerykan�w �ydowskiego pochodzenia planuje zamach na Hitlera.',
                       1, '2009-05-20', 14, 6);
INSERT INTO FILMY VALUES(FilmySeq.NEXTVAL, 'Incepcja', 'Czasy, gdy technologia pozwala na wchodzenie w �wiat sn�w. Z�odziej Cobb ma za zadanie wszczepi� my�l do �pi�cego umys�u.',
                       2, '2010-07-08', 10, 7);
INSERT INTO FILMY VALUES(FilmySeq.NEXTVAL, 'Kr�l Lew', 'Targany nies�usznymi wyrzutami sumienia po �mierci ojca ma�y lew Simba skazuje si� na wygnanie rezygnuj�c z przynale�nego mu miejsca na czele stada.',
                        3, '1994-06-15', 2, 8);
INSERT INTO FILMY VALUES(FilmySeq.NEXTVAL, 'Leon zawodowiec', 'P�atny morderca ratuje dwunastoletni� dziewczynk�, kt�rej rodzina zosta�a zabita przez skorumpowanych policjant�w.',
                        4, '1994-09-14', 4, 9);
INSERT INTO FILMY VALUES(FilmySeq.NEXTVAL,'Pianista','Podczas drugiej wojny �wiatowej W�adys�aw Szpilman, znakomity polski pianista, stara si� prze�y� w okupowanej Warszawie.', 4,'2002-05-04',3,10);

DROP SEQUENCE z;
CREATE SEQUENCE z;

INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 1);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 1);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 1);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 2);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 2);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 2);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 2);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 3);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 3);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 4);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 4);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 4);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 4);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 4);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 5);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 5);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 5);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 5);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 5);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 6);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 6);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 7);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 7);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 7);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 8);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 9);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 9);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 9);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 9);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 10);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 10);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 10);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 10);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 10);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 11);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 11);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 11);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 11);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 11);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 12);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 12);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 12);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 12);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 12);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 13);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 13);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 13);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 13);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 13);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 14);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 14);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 14);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 14);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 15);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 16);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 16);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 17);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 17);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 17);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 18);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 18);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 18);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 18);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 19);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 19);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 19);
INSERT INTO EGZEMPLARZ VALUES(z.NEXTVAL, 19);

DROP SEQUENCE KlientSeq;
CREATE SEQUENCE KlientSeq;

insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Matthew', 'Hansen', 'mhansen0@macromedia.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Mary', 'Boyd', 'mboyd1@ucoz.ru');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Jonathan', 'Fox', 'jfox2@geocities.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Anna', 'Matthews', 'amatthews3@yale.edu');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Barbara', 'Ramirez', 'bramirez4@privacy.gov.au');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Frank', 'Rice', 'frice5@slideshare.net');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Michelle', 'Perez', 'mperez6@uol.com.br');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Gregory', 'Fowler', 'gfowler7@yellowbook.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Nicholas', 'Wallace', 'nwallace8@spiegel.de');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Eugene', 'Garcia', 'egarcia9@cam.ac.uk');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Christine', 'Matthews', 'cmatthewsa@desdev.cn');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Mark', 'Burton', 'mburtonb@statcounter.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Peter', 'Carter', 'pcarterc@cmu.edu');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Philip', 'James', 'pjamesd@mit.edu');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Paula', 'Fernandez', 'pfernandeze@timesonline.co.uk');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Sara', 'West', 'swestf@digg.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Aaron', 'Price', 'apriceg@walmart.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Patrick', 'Gordon', 'pgordonh@oaic.gov.au');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Heather', 'Brooks', 'hbrooksi@cloudflare.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Justin', 'Burton', 'jburtonj@techcrunch.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'David', 'Sanchez', 'dsanchezk@dedecms.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Todd', 'Ross', 'trossl@fc2.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Arthur', 'Bennett', 'abennettm@foxnews.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Walter', 'Baker', 'wbakern@psu.edu');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Amy', 'Hawkins', 'ahawkinso@goo.ne.jp');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Benjamin', 'Mendoza', 'bmendozap@prweb.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Laura', 'Parker', 'lparkerq@upenn.edu');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Adam', 'Fernandez', 'afernandezr@dell.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Jesse', 'Campbell', 'jcampbells@rediff.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Catherine', 'Griffin', 'cgriffint@soup.io');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Jessica', 'Carr', 'jcarru@tripadvisor.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Nicole', 'Turner', 'nturnerv@miibeian.gov.cn');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Keith', 'Patterson', 'kpattersonw@utexas.edu');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Cheryl', 'Ortiz', 'cortizx@psu.edu');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Fred', 'Roberts', 'frobertsy@gov.uk');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Barbara', 'Watkins', 'bwatkinsz@arstechnica.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Joseph', 'Green', 'jgreen10@com.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Russell', 'Hayes', 'rhayes11@dedecms.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Christine', 'Bailey', 'cbailey12@ning.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Stephen', 'Wood', 'swood13@theguardian.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Denise', 'Knight', 'dknight14@oracle.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Shirley', 'Carr', 'scarr15@about.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Angela', 'Wells', 'awells16@bizjournals.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Wanda', 'Morgan', 'wmorgan17@slideshare.net');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Harold', 'Hamilton', 'hhamilton18@infoseek.co.jp');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Mark', 'Kennedy', 'mkennedy19@hhs.gov');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Lori', 'Vasquez', 'lvasquez1a@springer.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Catherine', 'Stanley', 'cstanley1b@baidu.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Joyce', 'Boyd', 'jboyd1c@illinois.edu');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Thomas', 'Howell', 'thowell1d@godaddy.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Sharon', 'Brown', 'sbrown1e@networksolutions.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Julia', 'Lane', 'jlane1f@si.edu');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Aaron', 'George', 'ageorge1g@cbslocal.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Steve', 'Jackson', 'sjackson1h@google.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Aaron', 'Cox', 'acox1i@technorati.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Kimberly', 'Hansen', 'khansen1j@lulu.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Teresa', 'Ferguson', 'tferguson1k@omniture.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Roger', 'Watkins', 'rwatkins1l@webeden.co.uk');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Bonnie', 'Mccoy', 'bmccoy1m@usnews.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Mildred', 'Boyd', 'mboyd1n@zimbio.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Emily', 'Medina', 'emedina1o@hhs.gov');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Earl', 'Mason', 'emason1p@earthlink.net');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Andrea', 'Warren', 'awarren1q@nbcnews.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Douglas', 'Franklin', 'dfranklin1r@bloglines.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Ronald', 'Jones', 'rjones1s@home.pl');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Chris', 'Morgan', 'cmorgan1t@adobe.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Martha', 'Morrison', 'mmorrison1u@google.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Carol', 'Frazier', 'cfrazier1v@reference.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Betty', 'Stevens', 'bstevens1w@infoseek.co.jp');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Heather', 'Stone', 'hstone1x@wisc.edu');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Elizabeth', 'Murphy', 'emurphy1y@oracle.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Carol', 'Stephens', 'cstephens1z@jalbum.net');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Betty', 'Bryant', 'bbryant20@eepurl.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Margaret', 'Ramos', 'mramos21@squidoo.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Marilyn', 'King', 'mking22@vimeo.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Jeffrey', 'George', 'jgeorge23@merriam-webster.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Joyce', 'Marshall', 'jmarshall24@wsj.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Lisa', 'Fox', 'lfox25@aboutads.info');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Heather', 'Vasquez', 'hvasquez26@vinaora.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Joyce', 'Kelley', 'jkelley27@hatena.ne.jp');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Thomas', 'Dixon', 'tdixon28@unicef.org');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Sandra', 'Parker', 'sparker29@squarespace.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Terry', 'Sanders', 'tsanders2a@phpbb.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Andrew', 'Carroll', 'acarroll2b@biblegateway.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Wayne', 'Turner', 'wturner2c@stumbleupon.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Roger', 'Meyer', 'rmeyer2d@issuu.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Michael', 'Coleman', 'mcoleman2e@mit.edu');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'David', 'Coleman', 'dcoleman2f@pbs.org');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Arthur', 'Ward', 'award2g@infoseek.co.jp');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Nicole', 'Hudson', 'nhudson2h@yolasite.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Donald', 'Collins', 'dcollins2i@cornell.edu');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Clarence', 'Rodriguez', 'crodriguez2j@sogou.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Jean', 'Castillo', 'jcastillo2k@canalblog.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Lawrence', 'Hernandez', 'lhernandez2l@amazon.de');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Joe', 'Morales', 'jmorales2m@home.pl');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Brian', 'Turner', 'bturner2n@cnet.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Virginia', 'Butler', 'vbutler2o@marriott.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Carl', 'Fowler', 'cfowler2p@whitehouse.gov');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Juan', 'Ross', 'jross2q@bluehost.com');
insert into KLIENT (ID_KLIENTA, IMIE, NAZWISKO, EMAIL) values (KlientSeq.NEXTVAL, 'Shirley', 'Thomas', 'sthomas2r@odnoklassniki.ru');

DROP SEQUENCE WypozyczenieSeq;
CREATE SEQUENCE WypozyczenieSeq;

insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-09-27', '2015-10-15');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-10-27', '2017-03-12');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-05-06', '2015-11-14');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-04-16', '2015-09-18');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-03-08', '2014-06-02');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-08-13', '2015-09-05');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-07-18', '2017-02-16');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-08-13', '2017-03-31');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-12-01', '2016-01-15');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-03-28', '2015-05-10');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-11-09', '2017-03-05');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2017-03-23', '2017-04-04');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-01-26', '2016-03-25');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-12-02', '2017-01-08');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-07-24', '2016-11-10');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-05-13', '2015-06-05');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2013-09-05', '2014-04-26');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-09-06', '2016-09-29');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-05-27', '2015-07-31');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-06-11', '2014-12-14');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2013-06-13', '2014-05-13');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-05-24', '2016-01-18');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-09-25', '2016-12-21');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-05-10', '2016-10-03');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-10-06', '2016-05-20');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-03-25', '2015-11-03');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-02-08', '2015-02-12');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-11-27', '2016-09-13');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-04-14', '2015-10-09');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-10-22', '2016-11-17');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-05-23', '2015-06-29');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-08-15', '2017-01-07');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-11-12', '2016-01-03');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-09-12', '2016-03-27');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2017-03-10', '2017-04-07');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-06-05', '2016-10-19');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-01-07', '2014-04-30');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-03-23', '2016-05-11');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-01-09', '2014-09-30');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-01-05', '2014-09-27');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-06-26', '2015-12-22');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-08-22', '2015-09-06');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-02-15', '2015-04-23');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-12-26', '2017-01-18');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-11-04', '2016-01-19');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-10-25', '2017-01-16');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-04-15', '2016-06-06');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-06-20', '2017-03-07');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-03-31', '2014-04-18');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-12-11', '2017-03-24');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-12-24', '2017-03-21');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-01-02', '2015-03-13');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-04-02', '2015-09-26');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-10-28', '2016-11-01');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-08-24', '2015-09-01');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-09-05', '2016-08-05');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-11-07', '2016-03-17');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-12-01', '2016-01-13');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-12-28', '2016-01-27');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-11-14', '2016-12-30');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-02-16', '2015-08-15');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-11-03', '2017-07-12');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-10-18', '2017-03-19');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-02-05', '2014-06-28');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2017-02-09', '2017-02-27');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-03-17', '2015-09-13');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-05-29', '2015-09-01');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-04-30', '2016-08-26');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-09-16', '2015-10-05');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-10-12', '2015-10-29');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-06-23', '2016-12-10');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-11-17', '2017-01-04');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-12-01', '2017-03-26');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-08-27', '2016-10-19');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-10-10', '2014-11-28');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-12-26', '2015-05-06');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-09-21', '2014-12-21');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-02-23', '2014-11-05');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-11-10', '2016-11-19');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-01-11', '2015-07-06');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-09-27', '2014-10-03');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-10-18', '2016-12-03');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-04-30', '2016-04-20');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-03-21', '2015-04-18');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-12-17', '2017-02-28');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-12-08', '2017-01-03');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2017-01-07', '2017-03-20');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-05-19', '2014-10-11');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-12-05', '2016-05-26');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-10-22', '2017-03-03');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-07-03', '2015-02-11');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-11-11', '2017-01-30');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-08-11', '2014-08-26');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-03-01', '2016-03-12');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2017-01-21', '2017-03-19');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-07-01', '2014-07-01');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-05-28', '2016-08-13');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-07-30', '2016-09-08');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-10-08', '2016-04-06');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-06-03', '2016-07-05');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-04-12', '2015-05-21');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-05-13', '2015-02-08');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-04-21', '2016-04-23');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-07-09', '2016-02-09');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-07-21', '2016-07-25');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-05-30', '2016-12-27');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-04-06', '2016-06-18');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-04-13', '2015-08-21');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-09-03', '2014-11-18');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-01-25', '2016-03-16');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-05-05', '2015-09-11');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2017-02-07', '2017-03-03');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-02-13', '2014-07-01');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-07-25', '2015-04-16');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-08-15', '2016-04-29');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-06-27', '2015-08-20');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-11-30', '2015-05-11');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-03-23', '2015-04-13');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-09-13', '2016-10-03');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-01-28', '2015-03-06');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-08-17', '2015-10-22');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-06-20', '2016-08-06');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-05-30', '2016-07-31');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-09-12', '2015-11-13');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-10-05', '2014-11-05');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-05-08', '2016-10-22');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-09-10', '2015-12-08');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-11-14', '2016-04-03');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-02-01', '2016-04-23');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-05-23', '2016-08-31');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-12-08', '2016-10-22');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-08-13', '2015-12-01');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-01-08', '2015-02-05');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-02-10', '2015-10-25');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-01-09', '2015-04-17');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-12-13', '2015-05-24');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-10-05', '2015-06-20');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-03-10', '2016-12-17');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-01-23', '2015-04-09');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-11-18', '2014-12-06');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-12-20', '2015-03-27');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-01-03', '2016-09-26');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-11-05', '2016-09-17');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2017-03-20', '2017-04-01');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-11-20', '2016-10-22');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-07-16', '2015-09-30');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2016-02-04', '2016-03-01');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-11-20', '2015-12-18');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2015-10-19', '2015-12-13');
insert into WYPOZYCZENIE (ID_WYPOZYCZENIA, DATA_WYPOZYCZENIA, DATA_ODDANIA) values (WypozyczenieSeq.NEXTVAL, '2014-04-05', '2014-12-05');

DROP SEQUENCE KontoSeq;
CREATE SEQUENCE KontoSeq;

insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'vperry0', 'X3Qv0cddK', 0, 1);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'wbaker1', 'uh2BBTAi1', 0, 2);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'lmurphy2', 'axYMeUY', 0, 3);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'sthomas3', 'JNtx3g5W', 0, 4);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'gperry4', 'Omb3hmi', 0, 5);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'jallen5', 'hOsB95lxul', 0, 6);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'kbowman6', 'jBIS1QAw8n', 0, 7);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'pcunningham7', 'sifJli', 0, 8);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'mphillips8', 'qSCzHsrOmjyr', 0, 9);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'ehart9', 'f3hhyckZcidY', 0, 10);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'nmasona', 'OHEnpn', 0, 11);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'tfosterb', 'AkTqy2WaXiq', 0, 12);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'hhayesc', 'lR2Nizw', 0, 13);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'lpayned', 'ZKFSBX08d', 0, 14);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'lgarrette', 'e3KZhqP9A', 0, 15);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'sporterf', 'Y88xZMIMev8', 0, 16);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'coliverg', 'fnni4O', 0, 17);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'gnelsonh', '9mTZJ3n', 0, 18);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'jrossi', 'Fa9v825GNET', 0, 19);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'jreynoldsj', 'n2lYwkMzugg1', 0, 20);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'apricek', 'YCCYwGA', 0, 21);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'hmartinl', 'xSWGS1ayK4u', 0, 22);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'mcrawfordm', 'Y0PGESKK', 0, 23);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'mrusselln', '9gyU1erJ', 0, 24);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'bburtono', 'fqXgPqbZ', 0, 25);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'jaustinp', 'SR7kcuORgWi', 0, 26);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'rburkeq', 'FLTLKn', 0, 27);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'jwatsonr', 'xmUDJHrYNDJ', 0, 28);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'swilliamss', 'r0Ic6T', 0, 29);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'lgardnert', 'V9uatd', 0, 30);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'jfranklinu', 'ERWDWrHqm', 0, 31);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'jjohnstonv', 'ZffNMmYl', 0, 32);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'phernandezw', 'eoDtSnr9VS', 0, 33);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'rgarrettx', 'iBQOWvqa3c', 0, 34);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'lkennedyy', 'ZRfW3asJv', 0, 35);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'arichardsz', 's6t3LSowZEhZ', 0, 36);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'ereynolds10', 'v8UTGq', 0, 37);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'adaniels11', '9GrpCUrKsq', 0, 38);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'wedwards12', 'AD8gjsq', 0, 39);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'kwatkins13', 'pe2foRQ', 0, 40);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'hpierce14', 'pAFu2Uu1H', 0, 41);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'aray15', 'w2AMl3viFas', 0, 42);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'ksims16', 'Ky9V5aNW7dj', 0, 43);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'jmorrison17', 'cDOoOMhlB', 0, 44);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'gcruz18', '1eikzujiCO3p', 0, 45);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'lwarren19', 'Rv1gexXjF', 0, 46);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'awilliams1a', 'NR81AQK', 0, 47);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'jhunter1b', 'wUuSDe60QE', 0, 48);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'cwarren1c', '1Nq3PK7y0', 0, 49);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'epowell1d', 'FiDpf8', 0, 50);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'mdean1e', 'bR1eZ87jp0K', 0, 51);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'njohnson1f', 'rKQISo', 0, 52);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'apalmer1g', 'uYmuCJ4', 0, 53);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'cburton1h', 'sYzqv7hyy', 0, 54);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'cscott1i', 'ULysxt', 0, 55);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'ksimpson1j', 'BqFLaN', 0, 56);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'abell1k', 'Ijq8KZfp', 0, 57);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'chanson1l', 'Tglcf7', 0, 58);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'mpatterson1m', 'y4BpxL', 0, 59);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'crichardson1n', 'fGxRnW', 0, 60);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'mcarpenter1o', '3FpdBfJOYAZh', 0, 61);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'pdixon1p', 'aDdcszw', 0, 62);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'rlawson1q', 'pj9D98BhvV0e', 0, 63);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'fberry1r', 'xum1v0', 0, 64);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'mlane1s', 'awRA696BO5i', 0, 65);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'ifernandez1t', 'Khimz41G', 0, 66);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'rduncan1u', 'sV77AT', 0, 67);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'ediaz1v', 'mZaPFl', 0, 68);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'fpeters1w', 'II1X53ZVEcVQ', 0, 69);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'ecoleman1x', 'A2On3ntuk', 0, 70);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'dprice1y', '8BCGnvIzjlii', 0, 71);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'areyes1z', 'AdYKX5V', 0, 72);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'kgarza20', '9HhzktI', 0, 73);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'bchavez21', 'S7Ink0gNOYNJ', 0, 74);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'ahanson22', '5shOaPTCIh9', 0, 75);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'lhawkins23', '6g3fw363pb2', 0, 76);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'rramirez24', 'c1wsQicpJ', 0, 77);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'pgonzales25', 'z99PtK0D8z', 0, 78);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'mallen26', 'zqyO9SYzpwY', 0, 79);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'cphillips27', 'FwjOPet', 0, 80);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'atucker28', 'zTrqPz', 0, 81);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'ahoward29', 'AybWa7evy', 0, 82);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'rlawson2a', 'c6pV9Ue', 0, 83);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'sortiz2b', '7I6scXYDvAmd', 0, 84);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'nkelley2c', 'raE2HDo1bHDc', 0, 85);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'mwest2d', '3r6J2j', 0, 86);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'nevans2e', '3IaJrUSVNtk4', 0, 87);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'lstevens2f', 'A3yelXWMgG', 0, 88);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'jjohnson2g', 'EGF0PrHneI6', 0, 89);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'scooper2h', 'z8VbF4L3vF', 0, 90);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'dfox2i', 'vbrEwTYcJVz5', 0, 91);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'jwelch2j', 'XS9E5Gmg4dDQ', 0, 92);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'jfreeman2k', 'wZtAay', 0, 93);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'ahart2l', 'KdqyVRYlD', 0, 94);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'abradley2m', 'WGFBqZiBe', 0, 95);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'pblack2n', '0rl65p', 0, 96);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'amcdonald2o', 'VyQY078CZ', 0, 97);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'klient', 'klient', 0, 98);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'pgreen2q', 'SDhkSyuj', 1, 99);
insert into KONTO (ID_KONTA, LOGIN, HASLO, CZY_ADMIN, ID_KLIENTA) values (KontoSeq.NEXTVAL, 'admin', 'admin', 1, 100);

insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (52, 5, 1);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (67, 35, 2);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (7, 28, 3);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (61, 54, 4);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (10, 16, 5);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (25, 94, 6);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (44, 14, 7);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (13, 17, 8);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (31, 23, 9);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (2, 70, 10);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (14, 17, 11);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (7, 83, 12);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (59, 77, 13);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (43, 84, 14);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (32, 8, 15);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (40, 21, 16);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (23, 30, 17);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (67, 41, 18);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (4, 33, 19);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (27, 38, 20);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (18, 17, 21);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (10, 8, 22);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (36, 79, 23);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (2, 57, 24);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (25, 25, 25);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (45, 45, 26);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (22, 62, 27);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (1, 3, 28);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (11, 51, 29);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (24, 40, 30);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (16, 50, 31);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (64, 95, 32);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (23, 61, 33);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (41, 100, 34);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (15, 93, 35);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (48, 88, 36);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (39, 33, 37);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (14, 46, 38);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (8, 81, 39);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (26, 30, 40);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (29, 4, 41);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (12, 99, 42);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (44, 68, 43);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (54, 47, 44);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (35, 97, 45);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (66, 11, 46);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (32, 17, 47);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (15, 96, 48);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (22, 49, 49);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (56, 66, 50);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (58, 84, 51);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (60, 38, 52);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (47, 52, 53);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (47, 46, 54);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (9, 73, 55);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (22, 33, 56);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (32, 38, 57);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (59, 83, 58);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (57, 88, 59);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (48, 46, 60);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (48, 56, 61);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (42, 46, 62);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (1, 37, 63);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (14, 45, 64);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (41, 13, 65);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (17, 89, 66);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (31, 16, 67);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (9, 85, 68);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (12, 7, 69);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (1, 48, 70);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (46, 60, 71);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (25, 98, 72);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (24, 94, 73);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (18, 38, 74);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (61, 8, 75);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (16, 27, 76);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (30, 44, 77);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (11, 79, 78);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (56, 56, 79);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (34, 33, 80);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (35, 50, 81);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (61, 74, 82);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (3, 5, 83);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (20, 47, 84);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (57, 91, 85);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (18, 43, 86);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (36, 44, 87);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (45, 64, 88);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (7, 7, 89);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (19, 30, 90);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (63, 75, 91);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (4, 48, 92);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (18, 74, 93);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (66, 11, 94);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (61, 65, 95);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (37, 27, 96);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (3, 54, 97);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (50, 18, 98);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (26, 16, 99);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (27, 84, 100);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (8, 64, 101);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (22, 78, 102);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (6, 27, 103);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (14, 63, 104);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (36, 5, 105);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (45, 95, 106);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (15, 77, 107);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (13, 78, 108);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (60, 9, 109);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (33, 41, 110);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (55, 2, 111);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (63, 59, 112);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (63, 32, 113);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (55, 9, 114);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (48, 98, 115);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (12, 86, 116);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (14, 68, 117);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (11, 58, 118);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (9, 51, 119);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (15, 75, 120);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (4, 4, 121);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (40, 12, 122);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (13, 43, 123);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (5, 58, 124);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (58, 94, 125);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (59, 18, 126);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (34, 74, 127);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (2, 92, 128);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (9, 1, 129);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (29, 3, 130);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (5, 100, 131);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (16, 88, 132);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (41, 61, 133);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (46, 35, 134);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (7, 10, 135);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (29, 39, 136);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (12, 46, 137);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (57, 84, 138);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (61, 68, 139);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (41, 39, 140);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (64, 43, 141);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (62, 29, 142);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (51, 24, 143);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (5, 96, 144);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (47, 100, 145);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (51, 33, 146);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (65, 100, 147);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (17, 46, 148);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (24, 41, 149);
insert into DANE_WYPOZYCZENIA (ID_EGZEMPLARZU, ID_KLIENTA, ID_WYPOZYCZENIA) values (3, 41, 150);
