INSERT INTO REZYSER VALUES(1, 'Frank', 'Darabont');
INSERT INTO REZYSER VALUES(2, 'Olivier', 'Nakache');
INSERT INTO REZYSER VALUES(3, 'Francis Ford', 'Coppola');
INSERT INTO REZYSER VALUES(4, 'Robert', 'Zemeckis');
INSERT INTO REZYSER VALUES(5, 'Peter', 'Jackson');
INSERT INTO REZYSER VALUES(6, 'Quentin', 'Tarantino');
INSERT INTO REZYSER VALUES(7, 'Christopher', 'Nolan');
INSERT INTO REZYSER VALUES(8, 'Rob', 'Minkoff');
INSERT INTO REZYSER VALUES(9, 'Luc', 'Besson');
INSERT INTO REZYSER VALUES(10, 'Roman', 'Polañski');
